name: Building app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

#     container:
#       image:  google/dart:latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      
      - name: Set up JDK 12.
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
        
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.20.2'
    
      - name: Install dependencies
        run: flutter pub get
        
      - name: Create apk
        run: flutter build apk
        
      - uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: ./build/app/outputs/flutter-apk
          
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: pruebas.segetic@gmail.com
          password: ${{secrets.PASSWORD}}
          subject: Job
          body: its a body
          to: angus68p_n944r@ludxc.com
          from: Luke skywalker
          content_type: text/html
          atachments: ./build/app/outputs/flutter-apk/app-release.apk
        
