name: Building app

on:
  push:
    branches: [ master ]
    tags: 
      - '*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      
      - name: Set up JDK 12.
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
        
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.20.2'
    
      - name: Install dependencies
        run: flutter pub get
        
      - name: Create apk
        run: flutter build apk
          
      - name: list
        run: ls -la

#       - uses: actions/upload-artifact@v1
#         with:
#           name: app-release.apk
#           path: ./build/app/outputs/flutter-apk/
          
      - name: Generate release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
        
